### PR TITLE
Billing page quantity update fix

### LINKED ISSUE #623: Payments: price is sometimes not correct
The price is sometimes not correct if you enter values quickly. We need to invalidate old PreviewInvoice queries if there is a new query.

### PR DESCRIPTION
**Pull request by itbel**
- setState is only called for the last promise in the array

resolves #623

### CODE REVIEW

File: components/Billing/Billing.tsx [hunk 1]
```diff
@@ -222,8 +224,15 @@ class BillingImpl extends JCComponent<Props, State> {
...
-      this.setState({ invoice: invoice.data.previewInvoice?.invoice })
+      this.setState({ invoiceQueue: [...this.state.invoiceQueue, newInvoice] }, async () => {
+        const currentIndex = this.state.invoiceQueue.length - 1
+        const invoice = await this.state.invoiceQueue[currentIndex]
+
+        if (currentIndex === this.state.invoiceQueue.length - 1) {
+          console.log({ invoice: invoice.data.previewInvoice?.invoice })
+          this.setState({ invoice: invoice.data.previewInvoice?.invoice })
+        }
+      })
```
Comment (itbel) [inline components/Billing/Billing.tsx:235]: if the length of invoiceQueue is changed while waiting for the promise to resolve, it is ignored.
