### PR TITLE
Fix race condition in EditableUrl component

### LINKED ISSUE #449: Bug creating zoom url
When I create a new zoom assignment in courses, there is a bug occurring where as I type into the field, the characters get jumbled and the url does not form as I typed it.
Screen Shot 2020-09-28 at 9 26 24 AM

### PR DESCRIPTION
**Pull request by JonEsparaz**
Closes #449.

The component now keeps internal state for the URL value and the `onBlur` prop triggers the mutation/context update. Did some refactoring too (as per usual).

### CODE REVIEW

File: components/Forms/EditableUrl.tsx [hunk 1]
```diff
@@ -9,54 +8,65 @@ interface Props {
...
       return (
         <TextInput
-          onChange={(value) => {
-            this.onChanged(value)
+          onChange={(e) => {
+            this.setState({ url: e.nativeEvent.text })
           }}
-          placeholder={this.props.placeholder}
-          multiline={this.props.multiline}
-          onStartShouldSetResponder={() => true}
```
Comment (GeorgeBellTMH) [inline components/Forms/EditableUrl.tsx:36]: These guys were for situations where it might be in a touchable opacity....not sure if this component has any of those situations...there may be a better way of doing this, but it was the only solution I could find at the time...
